baseURL = "https://ellybot0914.github.io"
DefaultContentLanguage = "zh" # Theme's display language, supports: en, fr, zh, zh-hant
languageCode = "zh-cn"
title = "EllyBot0914的博客"
copyright = "2021 EllyBot0914"
theme = "diary"
# googleAnalytics = "UA-123-45"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4

[params]
subtitle = "我不再玩悠悠球了"
enableGitalk = true

# Twitter Card and Open Graph settings
enableOpenGraph = true
enableTwitterCards = true
title = "My Blog" # will set 'og:site_name'
description = "My HomePage Description"  # will set 'og:description'
favicon = "/favicon/avatar.png"

[params.gitalk]
  owner = "EllyBot0914"
  repo = "git@github.com:EllyBot0914/EllyBot0914.github.io.gitalk-repo.git"
  client_id = "6f1a2b910977511cb7c9"
  client_secret = "5c638bb348ee2a70316c7ad583800ee4fa22c180"
[taxonomies]
   tag = "tags"
   category = "categories"

[params.utterances]
repo="your repo"
term="[ENTER TERM HERE]"
label="your label"
theme="github-light"

[[menu.main]]
url = "/categories"
name = "分类"
weight = 2
[[menu.main]]
url = "/tags"
name = "标签"
weight = 3
[[menu.main]]
url = "/posts"
name = "归档"
weight = 1
[[menu.main]]
url = "/index.xml"
name = "RSS 订阅"
weight = 4
